created universal curve component
ramsayinnovations/ramsay-site pull request #131
Opened 2021-01-01 09:37 UTC by kirti75waytech

@MaksymTaratuta55 @thecodeclimber I have resolve issue #99 under this PR. Please review it and let me know if any other modification needed in this PR.
Thanks

2021-01-04 09:10 UTC, MaksymTaratuta55 requested changes
Please, check my comments

2021-01-04 09:10 UTC, MaksymTaratuta55 commented on src/components/pages/home/callToAction/CallToActionLayout.jsx
> +    // if (formStatus === "success") {
Could you please clarify. why did you comment it?

2021-01-04 09:10 UTC, MaksymTaratuta55 commented on src/components/pages/home/callToAction/CallToActionLayout.jsx
> +    // if (formStatus === "error") {
Could you please clarify. why did you comment it?

2021-01-04 10:18 UTC, kirti75waytech commented on src/components/pages/home/callToAction/CallToActionLayout.jsx
> +    // if (formStatus === "success") {
@MaksymTaratuta55 I commented the above code because by default the success page was rendering. And I thought you would have a reason for rendering the success page by default, and also I thought you will work on this code later. So, for now I commented the code. Please let me know if  you want me to uncomment this code.

2021-01-04 11:40 UTC, MaksymTaratuta55 commented on src/components/pages/home/callToAction/CallToActionLayout.jsx
> +    // if (formStatus === "success") {
@kirti75waytech, You should uncomment it and change the "success" state to "initial" https://github.com/ramsayinnovations/ramsay-site/blob/1f5ff8e2db396de3c0d1b1ad7903692450749a82/src/components/pages/home/callToAction/CallToAction.jsx#L22

2021-01-04 12:10 UTC, kirti75waytech commented on src/components/pages/home/callToAction/CallToActionLayout.jsx
> +    // if (formStatus === "success") {
@MaksymTaratuta55 I have updated the PR with above changes. Please review it. 
Thanks

2021-01-04 12:10 UTC, kirti75waytech commented on src/components/pages/home/callToAction/CallToActionLayout.jsx
> +    // if (formStatus === "error") {
@MaksymTaratuta55 Updated the PR with the required changes.

2021-01-04 14:09 UTC, thecodeclimber commented
@MaksymTaratuta55 

Can you please resolve these conflicts.

2021-01-04 14:26 UTC, thecodeclimber commented
@MaksymTaratuta55 

can you also take care of these conflicts.  thanks.

2021-01-04 17:20 UTC, thecodeclimber commented
@kirti75waytech 
@MaksymTaratuta55 

Also with this issue I am not sure who should be resolving the conflicts.  Can you also decide amongts yourself who will be working on it?  Thanks.

If you have any questions -- please feel free to ask :).

2021-01-05 03:56 UTC, kirti75waytech commented
> @kirti75waytech
> @MaksymTaratuta55
> 
> Also with this issue I am not sure who should be resolving the conflicts. Can you also decide amongts yourself who will be working on it? Thanks.
> 
> If you have any questions -- please feel free to ask :).

@thecodeclimber I will fix the conflicts for this PR.

2021-01-05 09:13 UTC, kirti75waytech commented
@thecodeclimber I have resolved the conflicts for this PR. Please review it and merge it.
Thanks

2021-01-05 22:40 UTC, MaksymTaratuta55 approved these changes

2021-01-06 13:01 UTC, kirti75waytech commented
@thecodeclimber I have resolved the conflicts for this PR. But the deployment is getting failed. Please can you share vercel credentials. So, I can fix it.

2021-01-06 14:13 UTC, thecodeclimber commented
@kirti75waytech 

Thanks for working on this.  With that said, I have made some changes which I am going to upload.  Let's see where things stand after that.

2021-01-07 00:22 UTC, merged