created universal pattern component
ramsayinnovations/ramsay-site pull request #132
Opened 2021-01-01 10:34 UTC by kirti75waytech

@MaksymTaratuta55 @thecodeclimber I have resolved issue #102 under this PR. Please review it and let me know if any other modification is needed.
Thanks

2021-01-04 09:20 UTC, MaksymTaratuta55 requested changes

2021-01-04 09:20 UTC, MaksymTaratuta55 commented on src/components/elements/Pattern.jsx
> +    <img src={`/img/${classes.name}.svg`} className={classes.img} />
please, rename it from `${classes.name}.svg` to `imgName` and don't pass it in the `classes`

2021-01-04 09:20 UTC, MaksymTaratuta55 commented on src/components/elements/Pattern.jsx
> +    <img src={`/img/${classes.name}.svg`} className={classes.img} />
Or you can create **Pattern.constants.js** with 
```
export const patternImages = {
    leftPattern: "/img/pattern__cta--left.svg",
    rightPattern: "/img/.....",
    .....
}
```
And use it in `<img src={patternImages[imgName]}>`

2021-01-04 10:23 UTC, kirti75waytech commented on src/components/elements/Pattern.jsx
> +    <img src={`/img/${classes.name}.svg`} className={classes.img} />
Okay, sure @MaksymTaratuta55. I'll update the code as you have suggested.
Thanks

2021-01-04 14:26 UTC, thecodeclimber commented
@MaksymTaratuta55 

Can you please take care of these conflicts?  Thanks.

2021-01-04 17:18 UTC, thecodeclimber commented
@MaksymTaratuta55 
@kirti75waytech 

I am not sure who is suppossed to resolve these conflicts.  Can you two please discuss and decide who should resolve them?  Thanks.

2021-01-05 03:42 UTC, kirti75waytech commented
> @MaksymTaratuta55
> @kirti75waytech
> 
> I am not sure who is suppossed to resolve these conflicts. Can you two please discuss and decide who should resolve them? Thanks.

@thecodeclimber I will resolve conflicts for this PR.

2021-01-05 09:14 UTC, kirti75waytech commented
@thecodeclimber I have resolved the conflicts for this PR. Please review the code and merge this PR.
Thanks

2021-01-05 22:46 UTC, MaksymTaratuta55 approved these changes

2021-01-06 03:53 UTC, thecodeclimber commented
@kirti75waytech 

I made some changes to the `Pattern` component.  Here is a video showing what I did:  https://www.loom.com/share/8e025225dffc417596d34a284f51aca5

I am now going to merge the branch into `develop--clone`.

2021-01-06 03:53 UTC, merged