40 refactoring folder structure
ramsayinnovations/ramsay-site pull request #66
Opened 2020-12-24 06:36 UTC by kirti75waytech

Issues resolved under this branch are :

- #39
- #40
- #42
- #45
- #49
- #50
- #56
- #57
- #58
- #59

2020-12-24 12:59 UTC, MaksymTaratuta55 requested changes
Please check my comments

2020-12-24 12:59 UTC, MaksymTaratuta55 commented on src/pages/auth/login.jsx
First latter not the upper case in the file name

2020-12-24 12:59 UTC, MaksymTaratuta55 commented on src/pages/auth/register.jsx
First latter not the upper case in the file name

2020-12-24 12:59 UTC, MaksymTaratuta55 commented on src/pages/contact-us/index.jsx
> +
Could you please clarify why you need separate ContactUs and `contact-us/index.js`

2020-12-24 12:59 UTC, MaksymTaratuta55 commented on src/pages/contact-us/index.jsx
> +
Please rename `contact-us` folder with camel case `contactUs`

2020-12-24 13:34 UTC, kirti75waytech commented on src/pages/contact-us/index.jsx
> +
@MaksymTaratuta55 because `contact-us/index.js` is a route which has been created for a separate page called Contact page. Which you can access via /contact-us in the URL. Where as `ContactUs` is the component which is actually being rendered. Please let me know if you need any modifications in this?

2020-12-24 13:39 UTC, MaksymTaratuta55 commented on src/pages/contact-us/index.jsx
> +
@kirti75waytech, yes, my fault, didn't notice that it is a page. But could you please clarify why you need a folder for it?

2020-12-24 13:42 UTC, kirti75waytech commented on src/pages/contact-us/index.jsx
> +
@MaksymTaratuta55 Nothing specific reason but it was just my preference to keep it under a folder. Let me know your thoughts on this.

2020-12-24 13:43 UTC, kirti75waytech commented on src/pages/contact-us/index.jsx
> +
This is already fixed in the other PR, so I will skip it from here. @MaksymTaratuta55

2020-12-24 13:51 UTC, kirti75waytech commented on src/pages/auth/login.jsx
done

2020-12-24 13:51 UTC, kirti75waytech commented on src/pages/auth/register.jsx
done

2020-12-24 13:54 UTC, MaksymTaratuta55 commented on src/pages/contact-us/index.jsx
> +
@kirti75waytech, I think it could be just a file without folder

2020-12-24 13:56 UTC, MaksymTaratuta55 requested changes

2020-12-24 13:56 UTC, MaksymTaratuta55 commented on src/pages/api/Hello.js
> +
It doesn't react component, it shouldn't be capitalized

2020-12-25 04:26 UTC, kirti75waytech commented on src/pages/api/Hello.js
> +
@MaksymTaratuta55 I have updated the changes.

2020-12-25 05:06 UTC, kirti75waytech commented on src/pages/contact-us/index.jsx
> +
Okay @MaksymTaratuta55 I have updated it in issue: #64 and updated it's PR. Please review it and let me know if other changes are required.
Thanks

2020-12-25 09:37 UTC, MaksymTaratuta55 approved these changes

2020-12-25 20:35 UTC, merged